### PR TITLE
ci: smoke-test packaged desktop app launch to catch startup crashes

### LINKED ISSUE #19926: ci: smoke-test the packaged desktop app at launch to catch startup crashes
## Background

On 2026-07-02, desktop releases v0.22.0–v0.22.3 crashed immediately at launch: `dist/main.js` failed at load time with `Cannot find module '@vm0/api-contracts/contracts/zero-computer-use-plugins'` because PR #19814 added a workspace import to the main process while tsup's `noExternal` did not bundle `@vm0/*` packages. Fixed by PR #19895 (v0.22.4).

CI builds the packaged .app but never launches it, so a packaged-environment-only failure like this ships undetected. Dev mode cannot catch it (workspace deps resolve fine there).

## Proposal

Add a post-package smoke test to the desktop CI job:

1. After `electron-forge` packaging, launch the built app binary headlessly (e.g. with a flag/env to skip auth UI if needed).
2. Assert the main process stays alive for N seconds and/or emits a ready marker (log line or exit-code probe), failing the job if the process exits early.
3. Capture stdout/stderr on failure so the crash cause is visible in CI logs.

As a cheap complementary guard, add a build-output assertion that `dist/main.js` contains no unresolved external `require("@vm0/...")`, protecting the tsup `noExternal` config against regression.

## Acceptance criteria

- CI fails if the packaged desktop app's main process crashes during startup.
- The 2026-07-02 crash (unbundled workspace import) would have been caught by this check.
- Failure output includes the main-process error for diagnosis.

## Impact

Startup crashes in packaged builds are unrecoverable for end users (see companion issue on bootstrap self-healing): the auto-updater runs inside the main process, so a launch crash also kills the update path and forces manual reinstall. This check is the primary line of defense.

---
_Created from a Zero web chat postmortem discussion of the v0.22.0–v0.22.3 launch crash._

### PR DESCRIPTION
**Pull request by lancy**
## Summary

Closes #19926.

Desktop releases v0.22.0–v0.22.3 crashed at launch (`Cannot find module '@vm0/api-contracts/...'` at `dist/main.js` load time, introduced by #19814, fixed by #19895). CI built the .app but never launched it, so a packaged-environment-only startup crash shipped undetected — and because the auto-updater runs inside the main process, affected users could not self-heal and had to reinstall manually. This PR makes the desktop CI actually launch the packaged artifact.

## Changes

**App smoke mode** (`src/desktop-smoke-test.ts`, `src/main.ts`): when `VM0_DESKTOP_SMOKE_TEST=1`, the main process prints `[smoke-test] desktop main ready` at the end of the `app.whenReady()` initialization and quits cleanly (via `allowQuitWithoutConfirmation`). This exercises the full module-load path plus all startup initialization (protocol registration, auto-updater install, tray, computer-use launch gating) as a deterministic ready signal — no user-facing behavior change, the branch is dead unless the env var is set.

**Smoke-test script** (`scripts/smoke-test-packaged-app.js`): locates the packaged .app (shared locator extracted from `run-packaged-app.js` into `scripts/packaged-app-paths.js`), first statically asserts the packaged `dist/main.js` contains no unbundled `require("@vm0/` workspace references (guards the tsup `noExternal` config against regression), then launches the executable with the smoke flag and requires the ready marker + exit code 0 within 60s. On failure it dumps full stdout/stderr to the CI log.

**CI wiring** (`.github/workflows/desktop.yml`): runs the smoke test after both the production and PR-preview `forge make` steps, on both arm64 and x64 macOS runners (production smoke runs before the preview build wipes `out/`; the preview step passes `VM0_DESKTOP_PLATFORM_URL` so the locator resolves the dev identity). Expected added time ≈10–30s per artifact.

## Verification

- `pnpm -F @vm0/desktop check-types`, `lint`, new vitest, and `knip --workspace apps/desktop` all pass locally.
- `pnpm -F @vm0/desktop build:electron` confirms the bundled `dist/main.js` contains the ready-marker code and zero `require("@vm0/` occurrences (validating the static assertion against the current fixed config).
- The end-to-end launch path runs in this PR's own Desktop workflow (both arches, both artifacts) — that run is the real verification.

Had this check existed, the v0.22.0 crash would have failed CI at the "Smoke test production artifact launch" step instead of shipping.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by lancy** [comment]
LGTM


PR_AUTO_REVIEW_COMMIT: 6b5c1b930db17d891401c121ea274e048a37f2a2
PR_AUTO_REVIEW_VERDICT: LGTM

## Summary

Adds a real launch smoke test for the packaged desktop app in CI: a `VM0_DESKTOP_SMOKE_TEST=1` mode in the main process that prints a deterministic ready marker after full `whenReady()` initialization and quits cleanly, a runner script that statically asserts `dist/main.js` has no unbundled `require("@vm0/` references before launching the .app with a 60s ready timeout, and workflow steps for both production and PR-preview artifacts on both macOS architectures. Directly addresses the v0.22.0–v0.22.3 launch-crash class from #19926.

## Findings

- Smoke branch is inert without the env var; production behavior unchanged. Quit path correctly reuses `allowQuitWithoutConfirmation()` so the `before-quit` confirmation guard does not block CI.
- Production smoke step runs before the preview build wipes `out/`; preview step passes `VM0_DESKTOP_PLATFORM_URL` so the shared locator (`packaged-app-paths.js`, extracted from `run-packaged-app.js` without behavior change) resolves the dev identity.
- Failure paths (early exit, wrong exit code, missing marker, 60s timeout with SIGKILL) all dump full stdout/stderr to the CI log; no silent passes.
- Static bundle assertion guards the tsup `noExternal` config against the exact regression that shipped in #19814.
- No P0/P1 blockers found.

## Testing

- New vitest covers the smoke-mode env flag; `check-types`, `lint`, and `knip --workspace apps/desktop` pass.
- `build:electron` verified the bundle contains the ready marker and zero unbundled workspace requires.
- The end-to-end launch check executes in this PR's own Desktop workflow (arm64 + x64, production + preview artifacts) — its result is the authoritative verification.

**Comment by lancy** [comment]
CI smoke test caught a real packaged-launch crash on this branch's baseline: `dist/main.js` fails at load with `Cannot find module '@modelcontextprotocol/sdk/client/index.js'` because the MCP sdk imports added by #19814 (`desktop-filesystem-plugin.ts`) were left external by tsup while forge packaging excludes `node_modules` entirely. This affects the current packaged builds from main (including released 0.22.4/0.22.5), not just this branch.

Fixed in 5af3612: added `/^@modelcontextprotocol\/sdk\//` to tsup `noExternal` and extended the smoke script's static assertion to also forbid unbundled `require("@modelcontextprotocol/sdk/` references. Verified locally that the rebuilt bundle contains no unbundled requires (remaining regex matches are ajv codegen string literals, not runtime requires).

**Comment by lancy** [comment]
LGTM


PR_AUTO_REVIEW_COMMIT: 5af3612dfb035faf6c4c9c7dbbeeea23b8da70de
PR_AUTO_REVIEW_VERDICT: LGTM

## Summary

Since the previously reviewed commit (6b5c1b9), this adds a merge of latest main plus one fix commit (5af3612): bundle `@modelcontextprotocol/sdk` into the electron main bundle via tsup `noExternal`, and extend the smoke script's static assertion to also forbid unbundled `require("@modelcontextprotocol/sdk/` references. The fix responds to a real failure the new smoke test caught on its first CI run — the packaged app crashed at `dist/main.js` load because the MCP sdk imports from #19814 were left external while forge packaging excludes `node_modules`.

## Findings

- The `noExternal` addition (`/^@modelcontextprotocol\/sdk\//`) scopes to the sdk only; `@modelcontextprotocol/server-filesystem` stays external, which is correct — packaged builds resolve the filesystem server from `resourcesPath/mcp/index.mjs` (extraResource), and the `nodeRequire.resolve` fallback is dev-only.
- Static assertion prefixes now cover both known unbundled-require regressions (#19895's `@vm0/` and this one); remaining `require("ajv/...")` matches in the bundle are codegen string literals, not runtime requires, so no false positives.
- The smoke test demonstrably works: it failed CI on exactly the defect class it was built for. No P0/P1 blockers in the incremental diff.

## Testing

- Local rebuild (`build:electron`) confirms zero unbundled `@vm0/` or `@modelcontextprotocol/sdk/` requires in `dist/main.js`; prettier, oxlint, and `check-types` pass.
- Authoritative end-to-end verification is this PR's Desktop workflow: arm64 + x64 launch smoke of both production and preview artifacts on the fixed bundle.
