### ISSUE TITLE
fix(e2e): drain page route handlers before fixture teardown

### ISSUE THREAD

**Issue by seven332** [vm0-ai/vm0#32396]
## Problem and evidence

The `cli-e2e-02-playwright (features)` job in [run 34134415761](https://github.com/vm0-ai/vm0/actions/runs/34134415761/job/101783810284?pr=32385) failed in `dark theme > focused composer does not cast a dark veil`:

```text
route.fetch: Target page, context or browser has been closed
GET /api/user-preferences
e2e/playwright/tests/chat.spec.ts:29
```

The job reports one failed test and ten passed tests; it reports a route callback error, not a failed theme/focus/shadow assertion. The test added by #32351 (`a7ff47cfdb09d8370ed94ca0ffb788a6ea963dc5`) starts an asynchronous real upstream fetch, rewrites only the theme preference, and does not drain route handlers before the page fixture is destroyed. Dark mode can already be applied from the emulated system preference while the server preference read remains in flight. PR #32385 changes only runner doctor, the host collector, collector regressions and deployment documentation, not this test or its frontend/API dependencies.

The shared `e2e/playwright/fixtures.ts` currently owns preview cookies but no page-route teardown. The adjacent pinned-agent loading test also registers an asynchronous page route; it releases its gate in `finally` but does not await the handler. The standalone connector-card regression already drains routes with `behavior: "wait"` before closing its page.

## Requirements

- The fixture-managed page must remain alive until already-running page route handlers finish, on both successful and failed tests.
- Preserve real network and callback failures. Do not use `ignoreErrors`, blanket catches, retries, sleeps, longer timeouts or test skips as the fix.
- Preserve the existing dark-theme, focus, shadow and pinned-agent geometry assertions, real preview requests and shared-account isolation.
- Add deterministic browser/HTTP integration coverage for the fixture lifecycle, including in-flight requests and error visibility.
- No production UI, API, runner or deployment behavior changes.

## Acceptance criteria

- A delayed intercepted request that outlives a test body completes before its page/context closes.
- The same cleanup runs after an assertion failure; the original failure remains observable.
- A failing route callback is still reported as a failed test.
- E2E type checking, formatting and fixture integration tests pass; the deployed features lane validates the unchanged product assertions.

This is a standalone, single-PR test-infrastructure fix. It does not implement or close #32084 or alter PR #32385.

**Comment by seven332** [comment]
## Challenge Review: Framing

**Checkpoint:** `framing`
**Outcome:** `proceed`

The job log establishes a real test-infrastructure failure, not an assertion or runner failure. Repository inspection confirms the route callback has no completion owner; the theme assertion can pass before the preference fetch finishes. The issue correctly separates the triggering test introduced by #32351 from the unrelated changes in #32385. The current body already captures the evidence and scope; no cosmetic rewrite is needed.

One standalone PR is appropriate. Preserve real upstream failures and parallel account isolation, cover fixture completion and failure paths, and keep production code and CI retry policy out of scope. No parent, dependencies or competing open issue were found in the targeted search.

**Comment by seven332** [comment]
## Research Phase

The failed job contains one asynchronous `route.fetch` callback error at chat.spec.ts:29 and ten passed tests. The dark-theme test was introduced by #32351, not #32385. Its UI assertions can complete using the emulated system theme while GET user-preferences remains in flight. The shared fixture currently owns preview cookies but no route completion. The adjacent agent loading test releases its gate without awaiting callback completion; the standalone connector-card regression already explicitly drains routes.

Playwright documents `unrouteAll({ behavior: "wait" })` for finishing running handlers; `ignoreErrors` suppresses failures and is not equivalent. [Official API reference](https://playwright.dev/docs/api/class-page#page-unroute-all).

The existing `pnpm test` fixture integration entry point supports real Chromium, loopback HTTP and subprocess tests; CI installs Chromium before running it. Main is 8342a7181c and local migrations passed. No exact callback count or production outage is inferred from the log. Keep product assertions, real preview requests and parallel account isolation unchanged.

**Comment by seven332** [comment]
## Options Phase

1. Add explicit cleanup to each existing route-owning test scope. This is correct locally but duplicates the page-lifetime invariant and leaves future callers exposed.
2. Wrap the existing lazy page fixture and drain page routes before returning it to Playwright for destruction. This covers both consumers, preserves fixture options and errors, and can be tested through the actual runner/fixture boundary. Tests remain responsible for releasing their own gates.
3. Remove interception and use persisted product theme settings. This needs dedicated-account or serialized isolation because current feature tests share one user; it is unnecessary expansion for this lifecycle bug.

Option 2 best fits the current ownership boundary. No global ignore-errors cleanup, retries, timeout increases, eager auto-page creation or production changes are justified. A stuck callback should remain a visible teardown failure under existing deadlines.

**Comment by seven332** [comment]
## Plan Phase

Implement option 2 as a standalone PR closing only #32396:

1. Add real Playwright-runner integration coverage importing the actual shared fixture, with loopback HTTP and Chromium. Keep a routed request pending after test-body completion, observe callback completion before page closure, and assert subprocess failures for original assertion errors and genuine route callback errors. Use the existing `pnpm test` entry point; no skipped/expected-failure annotations.
2. Demonstrate failure without the fix. Wrap the existing lazy `page` fixture, await `use(page)`, and in `finally` await `page.unrouteAll({ behavior: "wait" })` before returning to Playwright's built-in page/context owner. Preserve errors and existing browser/context creation/options.
3. Document page-route completion ownership and the requirement to release test-controlled gates before teardown. Do not change the chat/agent assertions, real request transformation, manual-page ownership, account preferences or production code.
4. Validate with scoped Prettier, `cd e2e && pnpm check-types`, the complete `pnpm test` suite and repeated focused lifecycle checks. e2e has no standalone ESLint/Knip configuration. Deployed product validation comes from the PR features lane; unrelated Turbo/Rust/Python suites are outside scope.
5. Commit, push, open the fix PR, self-review, post current-head review and inspect CI/feedback. Do not merge or modify PR #32385.

Risk: teardown now waits for callbacks instead of aborting them. Gated tests retain gate-release ownership; genuinely stalled callbacks remain visible under existing timeouts. No new deadlines, retries, suppressions, API contracts, persisted state or user-flow changes.

The user's request to fix and submit supplies implementation approval after the plan checkpoint. Completion requires passing local lifecycle/error regression tests and an accurate current-head CI report.

**Comment by seven332** [comment]
## Challenge Review: Plan

**Checkpoint:** `plan`
**Outcome:** `proceed`

The latest Plan places route completion at the existing lazy page owner, preserving real page/context creation and errors. Scoped finally cleanup is a credible alternative, but the shared owner covers both observed consumers and allows an integration test of the actual fixed boundary. Product theme mutation would introduce unnecessary shared-account races.

The installed Playwright 1.60.0 source confirms that wait joins active handler invocations without setting the ignore-exception flag. Explicit test gates must be released first; manually created pages and context routes remain outside this owner. Real browser/subprocess tests must prove completion and failure visibility, including original assertion failure. Preserve existing deadlines and all deployed UI assertions.

No body rewrite or additional PR split is necessary. The user's fix-and-submit request authorizes implementation; merge is not authorized.
