### ISSUE TITLE
feat(desktop): crash-resilient bootstrap entry so auto-update survives main-process startup failures

### ISSUE THREAD

**Issue by lancy** [vm0-ai/vm0#19927]
## Background

Desktop releases v0.22.0–v0.22.3 (2026-07-02) crashed at launch because `dist/main.js` failed at module-load time (`Cannot find module '@vm0/api-contracts/...'`, introduced by PR #19814, fixed by PR #19895). Because the auto-updater (`update-electron-app` / Squirrel) is initialized inside the same main process — `installDesktopAutoUpdates()` runs only after `app.whenReady()` in `main.ts` — the process died before the updater ever started. Affected users could not self-heal via auto-update and must manually reinstall.

This is a single point of failure: the updater and the business logic live and die together.

## Proposal

Restructure the main-process entry into a minimal bootstrap:

1. **Bootstrap module** (new entry point in tsup config) with near-zero dependencies — Electron built-ins only, no workspace packages. It must be trivially safe to load.
2. Bootstrap initializes the auto-updater as early as possible (after `app.whenReady()`), independent of the rest of the app.
3. Bootstrap then loads the real main logic inside a `try/catch` (dynamic `require`/`import`). On load failure it:
   - reports the error (Sentry if safely loadable, else local log),
   - shows a dialog telling the user the app hit a startup error and an update will be installed when available,
   - keeps the process alive so the updater can download and apply a fixed release, then relaunch.

## Acceptance criteria

- A build where the main module throws at load time (e.g. simulated missing module) still checks for, downloads, and installs an update, then relaunches successfully.
- Normal startup behavior and update flow are unchanged.
- The bootstrap itself has no `@vm0/*` or other workspace imports (guarded by a test/lint assertion).

## Notes

- Companion issue: CI packaged-app launch smoke test (primary prevention); this issue is the recovery path when prevention fails.
- Care needed around single-instance lock, Squirrel first-run events on Windows (currently macOS-only feed), and not showing the broken app window in degraded mode.

---
_Created from a Zero web chat postmortem discussion of the v0.22.0–v0.22.3 launch crash._

**Comment by lancy** [comment]
Companion prevention issue (CI smoke test): #19926
