### PR TITLE
feat(desktop): crash-resilient bootstrap entry so auto-update survives main-process startup failures

### LINKED ISSUE #19927: feat(desktop): crash-resilient bootstrap entry so auto-update survives main-process startup failures
## Background

Desktop releases v0.22.0–v0.22.3 (2026-07-02) crashed at launch because `dist/main.js` failed at module-load time (`Cannot find module '@vm0/api-contracts/...'`, introduced by PR #19814, fixed by PR #19895). Because the auto-updater (`update-electron-app` / Squirrel) is initialized inside the same main process — `installDesktopAutoUpdates()` runs only after `app.whenReady()` in `main.ts` — the process died before the updater ever started. Affected users could not self-heal via auto-update and must manually reinstall.

This is a single point of failure: the updater and the business logic live and die together.

## Proposal

Restructure the main-process entry into a minimal bootstrap:

1. **Bootstrap module** (new entry point in tsup config) with near-zero dependencies — Electron built-ins only, no workspace packages. It must be trivially safe to load.
2. Bootstrap initializes the auto-updater as early as possible (after `app.whenReady()`), independent of the rest of the app.
3. Bootstrap then loads the real main logic inside a `try/catch` (dynamic `require`/`import`). On load failure it:
   - reports the error (Sentry if safely loadable, else local log),
   - shows a dialog telling the user the app hit a startup error and an update will be installed when available,
   - keeps the process alive so the updater can download and apply a fixed release, then relaunch.

## Acceptance criteria

- A build where the main module throws at load time (e.g. simulated missing module) still checks for, downloads, and installs an update, then relaunches successfully.
- Normal startup behavior and update flow are unchanged.
- The bootstrap itself has no `@vm0/*` or other workspace imports (guarded by a test/lint assertion).

## Notes

- Companion issue: CI packaged-app launch smoke test (primary prevention); this issue is the recovery path when prevention fails.
- Care needed around single-instance lock, Squirrel first-run events on Windows (currently macOS-only feed), and not showing the broken app window in degraded mode.

---
_Created from a Zero web chat postmortem discussion of the v0.22.0–v0.22.3 launch crash._

### PR DESCRIPTION
**Pull request by lancy**
Closes #19927

## Problem

Desktop releases v0.22.0–v0.22.3 crashed at launch because `dist/main.js` failed at module-load time (`Cannot find module '@vm0/api-contracts/...'`). The auto-updater was initialized inside that same bundle after `app.whenReady()`, so the process died before the updater ever started — affected users could not self-heal and had to reinstall manually.

## What changed

**New crash-resilient entry point.** `package.json#main` now points to `dist/bootstrap.js`, a minimal bundle (`src/bootstrap.ts`) whose import graph is restricted to Electron built-ins, `update-electron-app`, a lazily-loaded `@sentry/electron/main`, and a handful of dependency-free local modules (`config`, `desktop-update-feed`, `desktop-auto-updates`, `computer-use-types`, new `desktop-api-base-url`). It contains no `@vm0/*` workspace code.

**Bootstrap owns the auto-updater** (both normal and degraded startup). It loads the real main bundle with a synchronous runtime `require("./main.js")` — kept `external` in the tsup config so it is never inlined — and after `app.whenReady()` installs the updater using hooks exported by `main.ts` (`desktopUpdateHooks`, `notifyDesktopAutoUpdatesInstalled`, typed against the `DesktopMainModule` contract so it is enforced at compile time). Normal startup behavior is unchanged, including the "Check for Updates…" menu item state.

**Degraded mode** (`src/bootstrap-degraded.ts`) when the main bundle throws at load: acquire the single-instance lock, report the error to Sentry when a DSN is configured (else append to `<logs>/desktop-bootstrap-failure.log`), show a startup-error dialog telling the user to keep the app running, keep the process alive with no app window, and install a downloaded update immediately without the Restart/Later prompt (offline host state → silent restart policy).

**Guards** (acceptance criterion: bootstrap must never gain workspace imports):
- `scripts/check-bootstrap-bundle.mjs` runs after every `build:electron` and fails the build if `dist/bootstrap.js` contains `@vm0/` or lost the runtime `require("./main.js")`.
- `src/bootstrap-imports.test.ts` walks the static value-import graph from `bootstrap.ts` and pins the exact reachable file set.
- Desktop CI workflow now also asserts `dist/bootstrap.js` exists in packaged/zipped apps.

Note: the plan's ESLint `no-restricted-imports` guard was swapped for the import-graph test above — the desktop app lints with oxlint, and the source-level test plus the post-build bundle scan cover both the source and bundler-inlining failure modes.

## Scope

macOS-only, matching the current update feed (`desktop-update-feed.ts` is darwin-only). Windows/Squirrel first-run handling is deferred until the feed supports Windows. The packaged-app crash→update→relaunch smoke test is tracked by companion issue #19926.

## Verification

- New integration tests for degraded mode (single-instance quit, feed URL + silent install without prompt, Sentry vs local-log reporting, reinstall messaging when updates are unavailable) — 6 tests, plus the import-graph guard.
- `build:electron` run locally: bundle guard passes, `dist/bootstrap.js` has zero `@vm0/` occurrences and keeps the runtime require.
- `check-types`, `oxlint`, `knip --workspace apps/desktop`, and the touched desktop test files all pass locally; full suite runs in CI.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by lancy** [comment]
LGTM


PR_AUTO_REVIEW_COMMIT: abfe61f8c64dddcbc31f523fa69d4c33297b48ed
PR_AUTO_REVIEW_VERDICT: LGTM

## Summary

Moves the desktop main entry to a minimal crash-resilient bootstrap (`dist/bootstrap.js`) that owns the auto-updater and loads the real main bundle via a runtime `require("./main.js")` kept external in tsup. On main-bundle load failure it reports the error (Sentry or local log), shows a startup-error dialog, keeps the process alive, and silently installs a downloaded update — exactly the recovery path proposed in #19927 for the v0.22.0–v0.22.3 launch-crash incident.

## Findings

- Bootstrap import graph is verifiably free of `@vm0/*`: guarded at source level by `bootstrap-imports.test.ts` (pins the exact reachable file set) and at bundle level by `scripts/check-bootstrap-bundle.mjs` wired into `build:electron` (also asserts the runtime require survived bundling). This satisfies the issue's "test/lint assertion" acceptance criterion; the oxlint-based desktop app has no ESLint `no-restricted-imports`, so the test+scan pair is the right substitute.
- Normal-path behavior preserved: main.ts exports typed `desktopUpdateHooks`/`notifyDesktopAutoUpdatesInstalled` (compile-time `DesktopMainModule` contract), and the menu "Check for Updates…" enabled state is re-applied after the updater installs. `checkForDesktopUpdates` still works because Electron's `autoUpdater` is a process-wide singleton shared across both bundles.
- Degraded mode correctly avoids the Restart/Later prompt by reporting `OFFLINE_COMPUTER_USE_HOST_STATE` (silent-restart policy) and never creates an app window; single-instance lock handled.
- `resolveComputerUseApiBaseUrl` extraction into zero-dep `desktop-api-base-url.ts` keeps existing importers working via re-export; no behavior change.
- Sentry sourcemap upload and desktop CI packaged-app assertions extended to cover `dist/bootstrap.js`.
- Scope is macOS-only, matching the existing darwin-only update feed; Windows/Squirrel deferred as noted in the issue.

No P0/P1 blockers found.

## Testing

- 6 new integration tests for degraded mode (lock contention, feed URL + silent install, no-prompt update install, Sentry vs local-log reporting, reinstall messaging) plus the import-graph guard; all pass locally along with `desktop-auto-updates`, `window-policy`, and `desktop-auth-session` suites (96 tests).
- `build:electron` run locally: bundle guard passes, zero `@vm0/` occurrences in `dist/bootstrap.js`, runtime require intact.
- `check-types`, `oxlint`, `knip --workspace apps/desktop` clean. Full pipeline in CI.

**Comment by lancy** [comment]
LGTM


PR_AUTO_REVIEW_COMMIT: 562ad3cad0da6736a9b713fbd5adcb13e2d89073
PR_AUTO_REVIEW_VERDICT: LGTM

## Summary
Re-review of the rebased head. Content is identical to the previously approved commit, plus a clean rebase onto latest main that resolves the `tsup.electron.config.js` conflict with the packaged-app smoke test change (#19932).

- `src/bootstrap.ts` is the new `package.json#main`: it installs the auto-updater first, then loads `dist/main.js` behind a runtime `require`, falling back to `enterDegradedDesktopMode` if the main bundle throws — so a broken main bundle can still self-heal via auto-update.
- `scripts/check-bootstrap-bundle.mjs` guards the isolation invariant at build time (no `@vm0/` code inlined; `require("./main.js")` stays a runtime call), wired into `build:electron`.
- Conflict resolution keeps both sides of `noExternal`: the PR's `./main.js` external and main's `@modelcontextprotocol/sdk` regex.
- CI workflow asserts `dist/bootstrap.js` is present in packaged prod and preview artifacts.

## Findings
No P0/P1 blockers. Rebase introduces no semantic changes beyond the intended merge of both `tsup` config edits.

## Testing
- `bootstrap-imports.test.ts` enforces the restricted import graph of the bootstrap entry.
- `bootstrap-degraded.test.ts` covers the degraded-mode fallback path.
- Build-time bundle guard + packaged-app CI assertions (prod and preview) verify the runtime layout; the packaged launch smoke test from #19932 exercises bootstrap → main startup end-to-end.

**Comment by lancy** [comment]
LGTM


PR_AUTO_REVIEW_COMMIT: 5392c935d686dde671c886de16b84bb31a8a539d
PR_AUTO_REVIEW_VERDICT: LGTM

## Summary
Re-review after a conflict-free merge of latest main into the branch (post merge-queue ejection housekeeping). The PR's own diff is byte-identical to the previously approved head `562ad3c`; the merge commit only brings in two unrelated platform UI fixes from main (#19938, #19944).

The change itself: `package.json#main` moves to a minimal `dist/bootstrap.js` that installs the desktop auto-updater first and loads `dist/main.js` behind a runtime `require`, falling back to a degraded mode window when the main bundle fails to load — so a shipped broken main bundle can still self-heal via auto-update.

## Findings
No P0/P1 blockers. No semantic changes since the last LGTM.

## Testing
- `bootstrap-imports.test.ts` enforces the bootstrap entry's restricted import graph.
- `bootstrap-degraded.test.ts` covers the degraded-mode fallback.
- `scripts/check-bootstrap-bundle.mjs` guards bundle isolation at build time; CI asserts `dist/bootstrap.js` in packaged prod/preview artifacts and the packaged launch smoke test exercises bootstrap → main end-to-end.

**Comment by lancy** [comment]
LGTM


PR_AUTO_REVIEW_COMMIT: 7937ade0566212a8769610f4cf69f8a668faf8df
PR_AUTO_REVIEW_VERDICT: LGTM

## Summary
Re-review after merging latest main (only #19929, chat-thread event sourcing in api/platform — no overlap with this PR's desktop files). The PR's own diff is unchanged from the previously approved heads `562ad3c`/`5392c93`.

The change: `package.json#main` moves to a minimal `dist/bootstrap.js` that installs the desktop auto-updater before loading `dist/main.js` behind a runtime `require`, entering a degraded-mode window if the main bundle fails — so a shipped broken main bundle can still self-heal via auto-update.

## Findings
No P0/P1 blockers. The prior `build-macos-x64` failure was a smoke-test flake (app reached "desktop main ready" and updater ran; crash came from a network failure loading the desktop-auth page, unrelated to bootstrap) — CI is rerunning on this head.

## Testing
- `bootstrap-imports.test.ts` enforces the bootstrap entry's restricted import graph.
- `bootstrap-degraded.test.ts` covers the degraded-mode fallback.
- `scripts/check-bootstrap-bundle.mjs` guards bundle isolation at build time; CI asserts `dist/bootstrap.js` in packaged prod/preview artifacts and the packaged launch smoke test exercises bootstrap → main end-to-end.
